export const BIBLE_CANONICAL_ORDER: Record<string, number> = {
	// Old Testament (Protestant Canon)
	Gen: 1,
	Exod: 2,
	Lev: 3,
	Num: 4,
	Deut: 5,
	Josh: 6,
	Judg: 7,
	Ruth: 8,
	'1Sam': 9,
	'2Sam': 10,
	'1Kgs': 11,
	'2Kgs': 12,
	'1Chr': 13,
	'2Chr': 14,
	Ezra: 15,
	Neh: 16,
	Esth: 17,
	Job: 18,
	Ps: 19,
	Prov: 20,
	Eccl: 21,
	Song: 22,
	Isa: 23,
	Jer: 24,
	Lam: 25,
	Ezek: 26,
	Dan: 27,
	Hos: 28,
	Joel: 29,
	Amos: 30,
	Obad: 31,
	Jonah: 32,
	Mic: 33,
	Nah: 34,
	Hab: 35,
	Zeph: 36,
	Hag: 37,
	Zech: 38,
	Mal: 39,

	// Deuterocanonical / Apocryphal Books (approximate Catholic/Orthodox order)
	Tob: 40,
	Jdt: 41,
	'Esth Gr': 42,
	Wis: 43,
	Sir: 44,
	Bar: 45,
	'Let Jer': 46,
	Sus: 47,
	Bel: 48,
	'Pr Azar': 49,
	'1Mac': 50,
	'2Mac': 51,
	'1Esd': 52,
	'2Esd': 53,
	'Pr Man': 54,
	'3Mac': 55,
	'4Mac': 56,
	Ps151: 57,

	// New Testament
	Matt: 58,
	Mark: 59,
	Luke: 60,
	John: 61,
	Acts: 62,
	Rom: 63,
	'1Cor': 64,
	'2Cor': 65,
	Gal: 66,
	Eph: 67,
	Phil: 68,
	Col: 69,
	'1Thess': 70,
	'2Thess': 71,
	'1Tim': 72,
	'2Tim': 73,
	Titus: 74,
	Phlm: 75,
	Heb: 76,
	Jas: 77,
	'1Pet': 78,
	'2Pet': 79,
	'1John': 80,
	'2John': 81,
	'3John': 82,
	Jude: 83,
	Rev: 84,
	Other: 99
};

export const SHAKESPEARE_CHRONOLOGY: Record<string, number> = {
	// History Plays
	'1H6': 1591,
	'2H6': 1591,
	'3H6': 1591,
	R3: 1592,
	R2: 1595,
	Jn: 1596,
	'1H4': 1596,
	'2H4': 1597,
	H5: 1599,
	H8: 1612,
	// Comedies
	TGV: 1590,
	Shr: 1590,
	Err: 1594,
	LLL: 1594,
	MND: 1595,
	MV: 1596,
	Ado: 1598,
	Wiv: 1597,
	AYL: 1599,
	TN: 1601,
	Tro: 1602,
	MM: 1603,
	AWW: 1604,
	// Tragedies
	Tit: 1591,
	Rom: 1595,
	JC: 1599,
	Ham: 1600,
	Oth: 1603,
	KL: 1605,
	Mac: 1606,
	Tim: 1605,
	Ant: 1606,
	Cor: 1608,
	// Romances
	Per: 1607,
	Cym: 1609,
	WT: 1609,
	Tmp: 1610,
	TNK: 1613,
	STM: 1600,
	// Poems
	Ven: 1593,
	Luc: 1594,
	Son: 1609,
	PP: 1599,
	PhT: 1601,
	LC: 1609,
	Other: 9999
};

export const SHAKESPEARE_TITLE_MAP: Record<string, string> = {
	Ado: 'Much Ado About Nothing',
	Ant: 'Antony and Cleopatra',
	AWW: 'All’s Well That Ends Well',
	AYL: 'As You Like It',
	Cor: 'Coriolanus',
	Cym: 'Cymbeline',
	Err: 'The Comedy of Errors',
	Ham: 'Hamlet',
	'1H4': 'Henry IV, Part 1',
	'2H4': 'Henry IV, Part 2',
	H5: 'Henry V',
	'1H6': 'Henry VI, Part 1',
	'2H6': 'Henry VI, Part 2',
	'3H6': 'Henry VI, Part 3',
	H8: 'Henry VIII',
	JC: 'Julius Caesar',
	Jn: 'King John',
	KL: 'King Lear',
	LLL: 'Love’s Labour’s Lost',
	Luc: 'The Rape of Lucrece',
	Mac: 'Macbeth',
	MM: 'Measure for Measure',
	MND: 'A Midsummer Night’s Dream',
	MV: 'The Merchant of Venice',
	Oth: 'Othello',
	Per: 'Pericles, Prince of Tyre',
	PhT: 'The Phoenix and the Turtle',
	PP: 'The Passionate Pilgrim',
	R2: 'Richard II',
	R3: 'Richard III',
	Rom: 'Romeo and Juliet',
	Shr: 'The Taming of the Shrew',
	Son: 'Sonnets',
	TGV: 'The Two Gentlemen of Verona',
	Tim: 'Timon of Athens',
	Tit: 'Titus Andronicus',
	Tmp: 'The Tempest',
	TN: 'Twelfth Night',
	TNK: 'The Two Noble Kinsmen',
	Tro: 'Troilus and Cressida',
	Ven: 'Venus and Adonis',
	Wiv: 'The Merry Wives of Windsor',
	WT: 'The Winter’s Tale',
	LC: 'A Lover’s Complaint',
	STM: 'Sir Thomas More',
	Other: 'Other'
};

export const BIBLE_BOOK_TITLE_MAP: Record<string, string> = {
	// Old Testament
	Gen: 'Genesis',
	Exod: 'Exodus',
	Lev: 'Leviticus',
	Num: 'Numbers',
	Deut: 'Deuteronomy',
	Josh: 'Joshua',
	Judg: 'Judges',
	Ruth: 'Ruth',
	'1Sam': '1 Samuel',
	'2Sam': '2 Samuel',
	'1Kgs': '1 Kings',
	'2Kgs': '2 Kings',
	'1Chr': '1 Chronicles',
	'2Chr': '2 Chronicles',
	Ezra: 'Ezra',
	Neh: 'Nehemiah',
	Esth: 'Esther',
	Job: 'Job',
	Ps: 'Psalms',
	Prov: 'Proverbs',
	Eccl: 'Ecclesiastes',
	Song: 'Song of Songs',
	Isa: 'Isaiah',
	Jer: 'Jeremiah',
	Lam: 'Lamentations',
	Ezek: 'Ezekiel',
	Dan: 'Daniel',
	Hos: 'Hosea',
	Joel: 'Joel',
	Amos: 'Amos',
	Obad: 'Obadiah',
	Jonah: 'Jonah',
	Mic: 'Micah',
	Nah: 'Nahum',
	Hab: 'Habakkuk',
	Zeph: 'Zephaniah',
	Hag: 'Haggai',
	Zech: 'Zechariah',
	Mal: 'Malachi',

	// Deuterocanonical / Apocrypha
	Tob: 'Tobit',
	Jdt: 'Judith',
	'Esth Gr': 'Esther (Greek Additions)',
	Wis: 'Wisdom of Solomon',
	Sir: 'Sirach (Ecclesiasticus)',
	Bar: 'Baruch',
	'Let Jer': 'Letter of Jeremiah',
	Sus: 'Susanna',
	Bel: 'Bel and the Dragon',
	'Pr Azar': 'Prayer of Azariah',
	'1Mac': '1 Maccabees',
	'2Mac': '2 Maccabees',
	'1Esd': '1 Esdras',
	'2Esd': '2 Esdras',
	'Pr Man': 'Prayer of Manasseh',
	'3Mac': '3 Maccabees',
	'4Mac': '4 Maccabees',
	Ps151: 'Psalm 151',

	// New Testament
	Matt: 'Matthew',
	Mark: 'Mark',
	Luke: 'Luke',
	John: 'John',
	Acts: 'Acts',
	Rom: 'Romans',
	'1Cor': '1 Corinthians',
	'2Cor': '2 Corinthians',
	Gal: 'Galatians',
	Eph: 'Ephesians',
	Phil: 'Philippians',
	Col: 'Colossians',
	'1Thess': '1 Thessalonians',
	'2Thess': '2 Thessalonians',
	'1Tim': '1 Timothy',
	'2Tim': '2 Timothy',
	Titus: 'Titus',
	Phlm: 'Philemon',
	Heb: 'Hebrews',
	Jas: 'James',
	'1Pet': '1 Peter',
	'2Pet': '2 Peter',
	'1John': '1 John',
	'2John': '2 John',
	'3John': '3 John',
	Jude: 'Jude',
	Rev: 'Revelation',

	// Misc
	Other: 'Other'
};
