<script lang="ts">
	import Seo from '$lib/components/Seo.svelte';
	import AboutPageSchema from '$lib/components/seo/AboutPageSchema.svelte';
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();
	const { seo } = $derived(data);

	// This data would ideally come from your build process, but is hard-coded here for simplicity.
	const llmUsage = {
		'gemini-pro-2.5': ['C', 'D', 'E', 'G', 'I', 'J', 'K', 'M', 'O', 'Q', 'R', 'U', 'V', 'W', 'Y'],
		'gemini-2.5-flash': ['H', 'S'],
		'gpt-4o': ['A', 'L', 'N'],
		'gpt-4.1': ['F', 'P', 'Z'],
		'gpt-5.0-thinking': ['B', 'T']
	};
</script>

<Seo {...seo} />
<AboutPageSchema />

<div class="prose prose-slate mx-auto max-w-3xl">
	<h1 class="mb-8 text-3xl font-bold tracking-tight text-slate-800">About this Website</h1>

	<div class="font-serif">
		<h2>Purpose</h2>
		<p>
			This site is a modern, freely accessible version of Morris Palmer Tilley’s landmark
			<em>A Dictionary of the Proverbs in England in the Sixteenth and Seventeenth Centuries</em>.
			The original book is long out of print, but here it’s paired with powerful search, analysis
			tools, and links between related proverbs.
		</p>

		<h2>Source Material</h2>
		<p>
			The core content comes from the following work, made available by the
			<a
				href="https://hdl.handle.net/2027/mdp.39015016495585"
				target="_blank"
				rel="noopener noreferrer"
			>
				HathiTrust Digital Library
			</a>
			under a
			<a
				href="http://www.hathitrust.org/access_use#cc-by-nc-3.0"
				target="_blank"
				rel="noopener noreferrer"
			>
				Creative Commons Attribution-NonCommercial 3.0
			</a> license:
		</p>
		<blockquote
			class="not-prose rounded-lg border-l-4 border-slate-300 bg-slate-50 p-4 text-slate-600"
		>
			<p class="!mt-0">
				<em>A Dictionary of the Proverbs in England in the Sixteenth and Seventeenth Centuries</em
				><br />
				by Morris Palmer Tilley (1950, University of Michigan Press)
			</p>
		</blockquote>

		<h2 class="mt-8">Background</h2>
		<p>
			The project is entirely independent. It has no association with the University of Michigan or
			the original publication and is run by one person. It was partly inspired by <a
				href="https://johnsonsdictionaryonline.com/"
				target="_blank"
				rel="noopener noreferrer">Johnson’s Dictionary Online</a
			>.
		</p>

		<h2 id="extra-features" class="mt-8">Extra Features</h2>
		<p>
			The <strong>“Meaning &amp; Analysis”</strong> sections for each proverb are generated by large
			language models (LLMs) to offer fresh interpretations. The following models were used to create
			the analysis for each letter group:
		</p>
		<dl class="not-prose grid grid-cols-1 gap-x-8 gap-y-2 text-sm sm:grid-cols-1">
			{#each Object.entries(llmUsage) as [model, letters]}
				<div class="flex">
					<dt class="w-40 flex-shrink-0 font-semibold text-slate-800">{model}:</dt>
					<dd class="text-slate-600">{letters.join(', ')}</dd>
				</div>
			{/each}
		</dl>

		<p>
			The <strong>“Related Proverbs”</strong>
			lists are created using word-embeddings, which look for proverbs that share related language or
			ideas. The following model was used:<code>dengcao/Qwen3-Embedding-8B:Q8_0</code>.
		</p>
		<p>These features are entirely new and were not part of Tilley’s original work.</p>

		<h2 class="mt-8">Ongoing Work</h2>
		<p>
			The site contains 11,820 proverbs across 12,758 pages. The text was extracted from digital
			scans, so occasional transcription errors remain. These are corrected over time.
		</p>

		<h2 class="mt-8">Helping Out</h2>
		<p>
			If you enjoy the site, share a proverb on social media. Each one has a unique image taken from
			Tilley’s original and designed to look good in posts. You can also reach out using the <a
				href="/contact">contact form</a
			>.
		</p>

		<h2 class="mt-8">Privacy</h2>
		<p>
			There are no cookies, ads, or tracking scripts here. Basic visit counts come from Cloudflare
			Web Analytics, which is privacy-respecting and does not track individuals.
		</p>
	</div>
</div>
