import proverbs from '$lib/data/proverbs.json';
import similar_proverbs_json from '$lib/data/similar_proverbs.json';
import proverb_analyses_json from '$lib/data/proverb_analyses.json';
import { compareCitations } from '$lib/server/sorting';
import {
	SHAKESPEARE_CHRONOLOGY,
	BIBLE_CANONICAL_ORDER,
	BIBLE_BOOK_TITLE_MAP,
	SHAKESPEARE_TITLE_MAP
} from '$lib/constants/orderings';
import type {
	AnalysisEntry,
	Proverb,
	ProverbSummary,
	SimilarProverb,
	SimilarProverbWithSummary
} from '$lib/types';
import { slugify } from './utils';

export interface Keyword {
	name: string;
	slug: string;
	count: number;
}

// Type definition for the pre-calculated similarity map.
interface SimilarityMap {
	[key: string]: {
		top?: SimilarProverb[];
		bottom?: SimilarProverb[];
	};
}

interface AnalysisMap {
	[proverbId: string]: any[]; // An array of analysis objects
}

// --- Data Initialization ---
// All data processing happens once when the server starts.

// 1. Load and normalize all proverbs from the main JSON file.
const ALL_PROVERBS: Proverb[] = (proverbs as Proverb[]).map((p) => ({
	...p,
	proverb_id: p.proverb_id
}));

// 2. Create a map for fast, direct access to any proverb by its ID.
const PROVERBS_BY_ID = new Map<string, Proverb>(ALL_PROVERBS.map((p) => [p.proverb_id, p]));

// 3. Create a "summary" version of each proverb for list pages.
const ALL_SUMMARIES = new Map<string, ProverbSummary>(
	ALL_PROVERBS.map((p) => [
		p.proverb_id,
		{ proverb_id: p.proverb_id, proverb_text: p.proverb_text }
	])
);

// 4. Create an ordered list of all IDs for sequential navigation (prev/next).
const ORDERED_IDS = Array.from(PROVERBS_BY_ID.keys());

// 5. Load the pre-calculated similarity data.
const SIMILARITY_MAP: SimilarityMap = similar_proverbs_json as SimilarityMap;

const ALL_KEYWORDS: Keyword[] = (() => {
	const counts = new Map<string, number>();
	for (const p of ALL_PROVERBS) {
		if (p.proverb_keyword) {
			const keyword = p.proverb_keyword.trim();
			counts.set(keyword, (counts.get(keyword) || 0) + 1);
		}
	}
	const keywordList = Array.from(counts.entries())
		.map(([name, count]) => ({
			name,
			slug: slugify(name),
			count
		}))
		.filter((kw) => kw.count >= 3);
	return keywordList.sort((a, b) => b.count - a.count);
})();

const KEYWORD_BY_SLUG = new Map<string, Keyword>(ALL_KEYWORDS.map((k) => [k.slug, k]));

// Load the analyses data with the correct type
const ANALYSES_MAP: AnalysisMap = proverb_analyses_json as AnalysisMap;

// --- Public API ---
// These are the simple functions our application will use.

/**
 * Retrieves the full data for a single proverb by its ID.
 * Used on the main proverb detail page.
 */
export function getProverb(id: string): Proverb | undefined {
	return PROVERBS_BY_ID.get(id);
}

/**
 * Returns a list of all proverb summaries, used for filtering.
 */
export function getAllSummaries(): ProverbSummary[] {
	return Array.from(ALL_SUMMARIES.values());
}

export function getSummariesByLetter(letter: string): ProverbSummary[] {
	const requestedLetter = letter;
	return getAllSummaries().filter((p) => p.proverb_id.startsWith(requestedLetter));
}
/**
 * Returns a list of all proverb IDs.
 * Used for the "Random Proverb" feature.
 */
export function getAllIds(): string[] {
	return ORDERED_IDS;
}

/**
 * Finds the previous and next proverb IDs for sequential navigation.
 */
export function getNeighbours(id: string): { prev?: string; next?: string } {
	const idx = ORDERED_IDS.indexOf(id);
	if (idx === -1) return {};

	return {
		prev: idx > 0 ? ORDERED_IDS[idx - 1] : undefined,
		next: idx < ORDERED_IDS.length - 1 ? ORDERED_IDS[idx + 1] : undefined
	};
}

/**
 * Retrieves a list of thematically similar proverbs for a given ID.
 * Uses the pre-calculated map generated by the ML pipeline.
 */
export function getTopSimilar(id: string): SimilarProverbWithSummary[] {
	const similarEntries = SIMILARITY_MAP[id]?.top || [];

	return similarEntries
		.map((entry) => {
			const summary = ALL_SUMMARIES.get(entry.id);
			if (!summary) return null;
			return { ...entry, ...summary };
		})
		.filter((p): p is SimilarProverbWithSummary => !!p);
}

export function getBottomSimilar(id: string): SimilarProverbWithSummary[] {
	const similarEntries = SIMILARITY_MAP[id]?.bottom || [];

	return similarEntries
		.map((entry) => {
			const summary = ALL_SUMMARIES.get(entry.id);
			if (!summary) return null;
			return { ...entry, ...summary };
		})
		.filter((p): p is SimilarProverbWithSummary => !!p);
}

/**
 * Returns the full list of all keywords with their names, slugs, and counts.
 */
export function getKeywordIndex(): Keyword[] {
	return ALL_KEYWORDS;
}

/**
 * Returns a list of proverb summaries for a given keyword SLUG.
 */
export function getSummariesByKeywordSlug(slug: string): ProverbSummary[] {
	const keyword = KEYWORD_BY_SLUG.get(slug);
	if (!keyword) return [];

	const matchingProverbs = ALL_PROVERBS.filter(
		(p) => p.proverb_keyword?.trim().toUpperCase() === keyword.name.toUpperCase()
	);

	return matchingProverbs
		.map((p) => ALL_SUMMARIES.get(p.proverb_id))
		.filter((s): s is ProverbSummary => !!s);
}
export function getSummariesByFilter(filterType: string, filterValue: string): ProverbSummary[] {
	const value = filterValue.toUpperCase();

	const filtered = ALL_PROVERBS.filter((p) => {
		if (filterType === 'erasmus') {
			return !!p.initial_erasmus_citation;
		}
		if (filterType === 'don_quixote') {
			return p.quotations_list?.some(
				(q) =>
					(q.author?.toUpperCase() === 'SHELTON' && q.title?.toUpperCase().includes('DON')) ||
					(q.author?.toUpperCase() === 'MOTTEUX' && q.title?.toUpperCase().includes('QUIX')) ||
					(q.author?.toUpperCase().includes('URFEY') && q.title?.toUpperCase().includes('QUIX')) ||
					(q.author?.toUpperCase() === 'GAYTON' && q.title?.toUpperCase().includes('QUIX'))
			);
		}
		if (filterType === 'shelton_don_quixote') {
			return p.quotations_list?.some(
				(q) => q.author?.toUpperCase() === 'SHELTON' && q.title?.toUpperCase().includes('DON')
			);
		}
		if (filterType === 'italian_proverbs') {
			return p.quotations_list?.some(
				(q) => q.author?.toUpperCase().includes('TOR') && q.title?.toUpperCase().includes('IT.')
			);
		}
		if (filterType === 'british_proverbs') {
			return p.quotations_list?.some(
				(q) => q.author?.toUpperCase().includes('HOW') && q.title?.toUpperCase().startsWith('BR')
			);
		}
		if (filterType === 'english_proverbs') {
			return p.quotations_list?.some(
				(q) =>
					q.author?.toUpperCase().includes('HOW') && q.title?.toUpperCase().startsWith('ENG. P')
			);
		}
		if (filterType === 'spanish_proverbs') {
			return p.quotations_list?.some(
				(q) => q.author?.toUpperCase().includes('HOW') && q.title?.toUpperCase().startsWith('SP')
			);
		}
		if (filterType === 'french_proverbs') {
			return p.quotations_list?.some(
				(q) => q.author?.toUpperCase().includes('HOW') && q.title?.toUpperCase().startsWith('FR')
			);
		}
		if (filterType === 'benjamin_franklin') {
			return p.quotations_list?.some((q) => q.author?.toUpperCase().includes('FRANKLIN'));
		}
		if (filterType === 'john_milton') {
			return p.quotations_list?.some((q) => q.author?.toUpperCase().startsWith('MILTON'));
		}
		if (filterType === 'john_dryden') {
			return p.quotations_list?.some((q) => q.author?.toUpperCase().includes('DRYDEN'));
		}
		if (filterType === 'marlowe') {
			return p.quotations_list?.some((q) => q.author?.toUpperCase().includes('MARLOWE'));
		}
		if (filterType === 'swift') {
			return p.quotations_list?.some((q) => q.author?.toUpperCase().includes('SWIFT'));
		}
		if (filterType === 'chapman') {
			return p.quotations_list?.some((q) => q.author?.toUpperCase().includes('CHAPMAN'));
		}
		if (filterType === 'jonson') {
			return p.quotations_list?.some((q) => q.author?.toUpperCase().includes('JONSON'));
		}
		if (filterType === 'beaumont_fletcher') {
			return (
				p.quotations_list?.some((q) => q.author?.toUpperCase().includes('BEAUMONT')) &&
				p.quotations_list?.some((q) => q.author?.toUpperCase().includes('FLETCHER'))
			);
		}
		if (filterType === 'spenser') {
			return p.quotations_list?.some((q) => q.author?.toUpperCase().includes('SPENSER'));
		}
		if (filterType === 'dekker') {
			return p.quotations_list?.some((q) => q.author?.toUpperCase().includes('DEKKER'));
		}
		if (filterType === 'massinger') {
			return p.quotations_list?.some((q) => q.author?.toUpperCase().includes('MASSINGER'));
		}
		if (filterType === 'lyly') {
			return p.quotations_list?.some((q) => q.author?.toUpperCase().includes('LYLY'));
		}
		if (filterType === 'middleton') {
			return p.quotations_list?.some((q) => q.author?.toUpperCase().includes('MIDDLETON'));
		}
		if (filterType === 'greene') {
			return p.quotations_list?.some((q) => q.author?.toUpperCase().includes('GREENE'));
		}
		if (filterType === 'hobbes') {
			return p.quotations_list?.some((q) => q.author?.toUpperCase().includes('HOBBES'));
		}
		if (filterType === 'lestrange') {
			return p.quotations_list?.some((q) => q.author?.toUpperCase().includes('ESTRANGE'));
		}
		if (filterType === 'sidney') {
			return p.quotations_list?.some((q) => q.author?.toUpperCase().includes('SIDNEY'));
		}
		return false;
	});

	// Return summaries of the filtered proverbs
	return filtered.map((p) => ({
		proverb_id: p.proverb_id,
		proverb_text: p.proverb_text
	}));
}

export function getGroupedCitations(collectionType: 'shakespeare' | 'bible') {
	const type = collectionType;
	if (type === 'shakespeare') {
		const works = new Map<string, any[]>();
		ALL_PROVERBS.forEach((p) => {
			p.shakespeare_citations?.forEach((c) => {
				const workAbbr = c.title_abbr || 'Other';
				if (!works.has(workAbbr)) {
					works.set(workAbbr, []);
				}
				works.get(workAbbr)?.push({
					proverb_id: p.proverb_id,
					proverb_text: p.proverb_text,
					citation: c
				});
			});
		});

		return Array.from(works.entries())
			.map(([title_abbr, citations]) => ({
				title_abbr,
				full_title: SHAKESPEARE_TITLE_MAP[title_abbr] || title_abbr, // Add full title
				citations: citations.sort((a, b) => compareCitations(a, b, type))
			}))
			.sort(
				(a, b) =>
					(SHAKESPEARE_CHRONOLOGY[a.title_abbr] || 999) -
					(SHAKESPEARE_CHRONOLOGY[b.title_abbr] || 999)
			);
	}

	if (type === 'bible') {
		const books = new Map<string, any[]>();
		ALL_PROVERBS.forEach((p) => {
			if (p.initial_bible_citation) {
				const bookTitle = p.initial_bible_citation.book_title || 'Other';
				if (!books.has(bookTitle)) {
					books.set(bookTitle, []);
				}
				books.get(bookTitle)?.push({
					proverb_id: p.proverb_id,
					proverb_text: p.proverb_text,
					citation: p.initial_bible_citation
				});
			}
		});

		return Array.from(books.entries())
			.map(([book_title_abbr, citations]) => ({
				book_title: book_title_abbr,
				full_title: BIBLE_BOOK_TITLE_MAP[book_title_abbr] || book_title_abbr, // Add full title
				citations: citations.sort((a, b) => compareCitations(a, b, type))
			}))
			.sort(
				(a, b) =>
					(BIBLE_CANONICAL_ORDER[a.book_title] || 999) -
					(BIBLE_CANONICAL_ORDER[b.book_title] || 999)
			);
	}

	return [];
}

// Update the function to return a strongly typed array or undefined
export function getAnalysesForId(id: string): AnalysisEntry[] | undefined {
	return ANALYSES_MAP[id.toUpperCase()];
}
